title: Whip It Good
description: High-protein desserts, Ninja Creami recipes, and frozen treats.
url: https://whipitgoodfood.github.io   # your public site root
baseurl: /whipitgood                    # the repo/project path (keep the leading /)

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - category/creami.md
  - category/frozen-treats.md
  - category/protein-bakes.md
  - category/seasonal.md

permalink: /:categories/:title/
paginate: 6
paginate_path: "/page:num/"

# Optional social (helps jekyll-seo-tag)
twitter_username: ""
github_username: "whipitgoodfood"

# Defaults help SEO cards if a post ever misses image/alt
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: recipe
      image_alt: "Whip It Good recipe image"

# jekyll-feed config (so IFTTT/Pinterest can read your feed)
feed:
  path: feed.xml
