title: Whip It Good
description: High-protein desserts and frozen treats made easy.
theme: minima
author: Ricky
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
header_pages:
  - about.md
  - categories/frozen-treats.md
  - categories/protein-bakes.md
  - categories/creami.md
  - categories/seasonal.md
url: "https://whipitgoodfood.github.io"
baseurl: "/whipitgood"
