name: Generate recipe post

on:
  schedule:
    - cron: '15 16 * * *'   # daily 9:15am PT (16:15 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pillow pyyaml requests

      - name: Generate post
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          SITE_BASE: "https://whipitgoodfood.github.io/whipitgood"
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
        run: |
          set -euxo pipefail
          python scripts/generate_recipe.py

      - name: Commit & push changes
        run: |
          set -euxo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore: auto-generate recipe post"
          git push
